/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Endpoint
         * @description Accepts a user message, updates the chat history,
         *     processes the message via the internal engine, and returns:
         *       - updated chat history
         *       - entire research graph (nodes and edges)
         */
        post: operations["chat_endpoint_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Node
         * @description Manually add a node to the research graph.
         */
        post: operations["add_node_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Node
         * @description Manually delete a node (and any associated edges) from the research graph.
         */
        delete: operations["delete_node_nodes__node_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatMessage */
        ChatMessage: {
            /** Message */
            message: string;
            /** Role */
            role: string;
            /** Id */
            id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ChatMessageCreate */
        ChatMessageCreate: {
            /** Message */
            message: string;
        };
        /** ChatMessageOut */
        ChatMessageOut: {
            /** Chat History */
            chat_history: components["schemas"]["ChatMessage"][];
            graph: components["schemas"]["Graph"];
        };
        /** Edge */
        Edge: {
            /** From Node Id */
            from_node_id: string;
            /** To Node Id */
            to_node_id: string;
            /** Id */
            id: string;
        };
        /** Graph */
        Graph: {
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Edges */
            edges: components["schemas"]["Edge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Node */
        Node: {
            /** Node Class */
            node_class: string;
            content: components["schemas"]["NodeContent"];
            /** Id */
            id: string;
        };
        /** NodeContent */
        NodeContent: {
            /** Text */
            text: string;
            metadata: components["schemas"]["NodeMetadata"];
        };
        /** NodeCreate */
        NodeCreate: {
            /** Node Class */
            node_class: string;
            content: components["schemas"]["NodeContent"];
        };
        /** NodeMetadata */
        NodeMetadata: {
            /** Source */
            source: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_endpoint_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_node_nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
